# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f1fb88862e6e14a61ccced5e7415ce09610ad2603c7dd81be6a9494713096e5f931eacd7503999c96dc7ce9363e755fe511204aa811f21f18a9a77aecda0eca

test:
  secret_key_base: 524d42cdc6430ac7debe245584792d991afa819284cdf0de308915fe1fb53d8654cf759e384fac95e78a7d8ca63dc175c88c93efe81c57972b9dc465c8dee92b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
